server:
  servlet:
    context-path: /api

spring:
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/minio?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

minio:
  endpoint: http://192.168.133.1:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucket: user-bucket


